### **K Nearest Neighbour CLassifier**

In [1]:
import numpy as np
import seaborn as sb
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline


In [2]:
from sklearn.datasets import make_classification

X,y = make_classification(
    n_samples=1000,
    n_features=3,
    n_redundant=1,
    n_classes=2,
    random_state=999
)

In [4]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]], shape=(1000, 3))

In [3]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [4]:
from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [6]:
def print_metrics(y_pred, y_true):
    from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
    print("Accuracy Score is")
    print(accuracy_score(y_pred,y_true))
    print("Classification Report is")
    print(classification_report(y_pred,y_true))
    print("Confusion Matrix is")
    print(confusion_matrix(y_pred,y_true))

print_metrics(y_pred,y_test)

Accuracy Score is
0.9066666666666666
Classification Report is
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       162
           1       0.88      0.93      0.90       138

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300

Confusion Matrix is
[[144  18]
 [ 10 128]]


In [8]:
### Task - GridSearchCV
def print_metrics(y_pred, y_true):
    from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
    print("Accuracy Score is")
    print(accuracy_score(y_pred,y_true))
    print("Classification Report is")
    print(classification_report(y_pred,y_true))
    print("Confusion Matrix is")
    print(confusion_matrix(y_pred,y_true))


from sklearn.model_selection import GridSearchCV

param_grid={"n_neighbors":[1,2,3,4,5,6,7,8,9],"algorithm":["auto"],"p":[1,2]}

knn = GridSearchCV(KNeighborsClassifier(),param_grid=param_grid,refit=True,cv=5)

knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
print_metrics(y_pred_knn,y_test)
print(knn.best_params_)


Accuracy Score is
0.9133333333333333
Classification Report is
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       158
           1       0.90      0.92      0.91       142

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300

Confusion Matrix is
[[143  15]
 [ 11 131]]
{'algorithm': 'auto', 'n_neighbors': 9, 'p': 1}
