## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

## Load the Data
- The Wine dataset contains 178 samples with 13 features related to chemical properties.
- The target variable indicates the class of the wine (class_0, class_1, or class_2).

In [2]:
wine = load_wine()
X = wine.data  # Features
y = wine.target  # Target variable

# Create a DataFrame for better visualization
wine_df = pd.DataFrame(data=X, columns=wine.feature_names)
wine_df['target'] = y
wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [7]:
print(wine['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

## Split the Data
- The train_test_split function divides the dataset into training (80%) and testing (20%) subsets.

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Train the Voting Classifier
- A Voting Classifier is initialized using three different models: Decision Tree, Logistic Regression, and SVM.

In [4]:
voting_model = VotingClassifier(
    estimators=[
        ('dt', DecisionTreeClassifier(random_state=42)),
        ('lr', LogisticRegression(max_iter=20000, random_state=42)),
        ('svc', SVC(probability=True, random_state=42))
    ],
    voting='soft'  # Use soft voting for better probabilities
)
voting_model.fit(X_train, y_train)

VotingClassifier(estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                             ('lr',
                              LogisticRegression(max_iter=20000,
                                                 random_state=42)),
                             ('svc', SVC(probability=True, random_state=42))],
                 voting='soft')

## Make Predictions & Evaluate the Model
- The predict method generates predictions for both the training and testing datasets.
- The model's performance is evaluated using confusion matrix and classification report.

In [5]:
y_train_pred = voting_model.predict(X_train)
y_test_pred = voting_model.predict(X_test)


print("Confusion Matrix: Train Data")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report (Train):")
print(classification_report(y_train, y_train_pred))

print("============================================================================")

print("Confusion Matrix: Test Data")
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification Report (Test):")
print(classification_report(y_test, y_test_pred))

Confusion Matrix: Train Data
[[45  0  0]
 [ 0 57  0]
 [ 0  0 40]]

Classification Report (Train):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        57
           2       1.00      1.00      1.00        40

    accuracy                           1.00       142
   macro avg       1.00      1.00      1.00       142
weighted avg       1.00      1.00      1.00       142

Confusion Matrix: Test Data
[[13  1  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.93      1.00      0.97        14
           2       1.00      1.00      1.00         8

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36



In [31]:
X_test.shape

(36, 13)

In [6]:
voting_model.named_estimators_['dt'].predict_proba(X_test)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [7]:
voting_model.named_estimators_['lr'].predict_proba(X_test)

array([[9.96727588e-01, 1.25422070e-03, 2.01819150e-03],
       [9.99045457e-01, 1.13700528e-05, 9.43172656e-04],
       [1.15772230e-02, 1.26111480e-01, 8.62311297e-01],
       [9.99806711e-01, 2.64270812e-05, 1.66861842e-04],
       [1.75611724e-03, 9.96669897e-01, 1.57398604e-03],
       [9.99619168e-01, 1.75127434e-06, 3.79080774e-04],
       [4.56239239e-04, 9.99442286e-01, 1.01474636e-04],
       [6.82932330e-03, 8.75776307e-05, 9.93083099e-01],
       [3.14068102e-03, 9.96825570e-01, 3.37493909e-05],
       [7.67730475e-02, 9.13090883e-03, 9.14096044e-01],
       [7.80167786e-01, 2.18103652e-01, 1.72856197e-03],
       [1.86372055e-04, 6.46143873e-05, 9.99749014e-01],
       [9.98578572e-01, 5.94772804e-04, 8.26655023e-04],
       [1.51460136e-03, 9.78786112e-01, 1.96992863e-02],
       [9.99704227e-01, 2.53711194e-07, 2.95518852e-04],
       [1.09295547e-05, 9.99964675e-01, 2.43950613e-05],
       [9.30666677e-06, 9.99924280e-01, 6.64129393e-05],
       [1.07560443e-04, 9.99765

In [8]:
voting_model.named_estimators_['svc'].predict_proba(X_test)

array([[0.46031013, 0.2795604 , 0.26012947],
       [0.93314899, 0.04103218, 0.02581883],
       [0.03223017, 0.54105144, 0.42671838],
       [0.97835003, 0.01430235, 0.00734762],
       [0.01360249, 0.58454415, 0.40185336],
       [0.97811631, 0.01447952, 0.00740417],
       [0.02222879, 0.55993247, 0.41783874],
       [0.18264357, 0.41633152, 0.40102491],
       [0.08017586, 0.48764316, 0.43218098],
       [0.25184372, 0.37823171, 0.36992456],
       [0.45754559, 0.2795738 , 0.2628806 ],
       [0.01273122, 0.588055  , 0.39921378],
       [0.89990801, 0.05934811, 0.04074388],
       [0.0059111 , 0.63649168, 0.35759722],
       [0.97910689, 0.01394305, 0.00695005],
       [0.00513849, 0.65087478, 0.34398672],
       [0.00795471, 0.61484688, 0.37719841],
       [0.04532635, 0.52324532, 0.43142833],
       [0.90903132, 0.05441527, 0.03655341],
       [0.0062186 , 0.63218567, 0.36159573],
       [0.92772598, 0.05049761, 0.0217764 ],
       [0.01276299, 0.58797212, 0.39926488],
       [0.

In [9]:
voting_model.predict_proba(X_test)

array([[0.81901257, 0.09360487, 0.08738255],
       [0.97739815, 0.01368118, 0.00892067],
       [0.01460247, 0.22238764, 0.76300989],
       [0.99271891, 0.00477626, 0.00250483],
       [0.00511954, 0.86040468, 0.13447578],
       [0.99257849, 0.00482709, 0.00259442],
       [0.00756168, 0.85312492, 0.1393134 ],
       [0.06315763, 0.13880637, 0.798036  ],
       [0.02777218, 0.82815624, 0.14407158],
       [0.10953892, 0.12912087, 0.7613402 ],
       [0.41257113, 0.49922582, 0.08820306],
       [0.3376392 , 0.19603987, 0.46632093],
       [0.96616219, 0.01998096, 0.01385684],
       [0.00247523, 0.87175926, 0.1257655 ],
       [0.99293704, 0.00464777, 0.00241519],
       [0.00171647, 0.88361315, 0.11467037],
       [0.00265467, 0.87159039, 0.12575494],
       [0.01514464, 0.84100351, 0.14385185],
       [0.96956216, 0.01814895, 0.01228889],
       [0.00207936, 0.87737603, 0.1205446 ],
       [0.97590832, 0.01683254, 0.00725914],
       [0.01288396, 0.85392204, 0.133194  ],
       [0.

In [10]:
voting_model.named_estimators_['svc'].score(X_train,y_train)

0.6901408450704225

In [11]:
voting_model.named_estimators_['svc'].score(X_test,y_test)

0.8055555555555556