### NumPy
* NumPy is a fundamental library for scientific computing in Python.
* It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
# 1D Array
arr2 = np.array([1,2,3,5,7])
arr2.reshape((1,5))

array([[1, 2, 3, 5, 7]])

In [4]:
arr2.reshape((1,4))

ValueError: cannot reshape array of size 5 into shape (1,4)

In [5]:
## 2D Array
arr3 = np.array([[1, 2, 3, 5, 7]])
print(arr3)
print(arr3.shape)

[[1 2 3 5 7]]
<class 'numpy.ndarray'>
(1, 5)


In [8]:
## Another 2D Array
arr4 = np.array([[1, 2, 3, 4, 5],[2, 3, 4, 5, 6]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
arr6 = np.arange(0, 10, 2).reshape((5,1))
print(arr6)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
## Attributes of NumPy Array

arr7 = np.array([[1,2,3],[4,5,6]])
print('Array: \n', arr7)
print('Shape: \n', arr7.shape)
print('Number of Dimensions: \n', arr7.ndim)
print('Size(Number of elements): \n', arr7.size)
print('Data Type: \n', arr7.dtype)
print('Item size(in bytes): \n', arr7.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: 
 (2, 3)
Number of Dimensions: 
 2
Size(Number of elements): 
 6
Data Type: 
 int64
Item size(in bytes): 
 8


In [23]:
## NumPy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element-Wise Addition
print(f'Addition : {arr1 + arr2}')

## Element-Wise Subtraction
print(f'Subtraction : {arr1 - arr2}') 

## Element-Wise Multiplication
print(f'Multiplication : {arr1 * arr2}') 

## Element-Wise Division
print(f'Division : {arr1 / arr2}') 

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [26]:
## Universal Functions
arr3 = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr3))

## square root
print(np.exp(arr3))

## square root
print(np.sin(arr3))

## square root
print(np.log(arr3))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
## Array Slicing and Indexing
import numpy as np
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"Array \n {arr4}")
print(arr4[0])
print(arr4[0][0])
print(arr4[1:,2:])
print(arr4[:2,2:]) #[[3 4] [7 8]]
print(arr4[1:,:2]) #[[5 6] [9 10]]
print(arr4[1:,1:3]) #[[6 7] [10 11]]

Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
1
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 5  6]
 [ 9 10]]
[[ 6  7]
 [10 11]]


In [18]:
## Modify the array elements
arr4[0][0] = 100
print(arr4)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr4[1:] = 100
print(arr4)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [20]:
## Statistical Concept - Normalization
## To have a mean of 0 and Standard Deviation of 1
data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the Data
normalized_data = (data - mean)/std_dev
print(f'Normalized data : {normalized_data}')

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
## Another Statistical Example
data = np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
mean = np.mean(data)
print(f'mean -> {mean}')

## Medain
median = np.median(data)
print(f'Median -> {median}')

## Standard Deviation
std_dev = np.std(data)
print(f'Standard Deviation -> {std_dev}')

## Variance
variance = np.var(data)
print(f'Variance -> {variance}')

mean -> 5.5
Median -> 5.5
Standard Deviation -> 2.8722813232690143
Variance -> 8.25


In [27]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[((data>=5) & (data<=8))]

array([5, 6, 7, 8])